import { useState, useEffect } from "react";
import { useAuth } from "../context/AuthContext";
import Layout from "../components/Layout";
import LoadingSpinner from "../components/LoadingSpinner";
import { useToastStore } from "../store/useToastStore";
import { API_URL } from "../config";

function PostmortemsPage() {
    const { token } = useAuth();
    const [postmortems, setPostmortems] = useState([]);
    const [loading, setLoading] = useState(true);
    const addToast = useToastStore((state) => state.addToast);

    useEffect(() => {
        const fetchPostmortems = async () => {
            try {
                const response = await fetch(`${API_URL}/api/postmortems`, {
                    headers: { Authorization: `Bearer ${token}` }
                });
                const data = await response.json();
                if (Array.isArray(data)) setPostmortems(data);
            } catch (error) {
                addToast("Failed to load postmortems", "error");
            } finally {
                setLoading(false);
            }
        };

        fetchPostmortems();
    }, [token]);

    if (loading) return <Layout><LoadingSpinner message="Loading postmortems..." /></Layout>;

    return (
        <Layout>
            <h1 className="text-xl font-semibold text-white mb-6">Postmortems</h1>

            <div className="flex flex-col gap-4">
                {postmortems.length === 0 ? (
                    <p className="text-gray-500 text-sm">No postmortems yet.</p>
                ) : (
                    postmortems.map((pm) => (
                        <div key={pm._id} className="bg-gray-900 border border-gray-800 rounded-xl p-5">
                            <p className="text-sm text-gray-300 mb-2">
                                <span className="font-medium text-gray-100">Root cause: </span>
                                {pm.rootCause}
                            </p>
                            <p className="text-sm text-gray-300 mb-2">
                                <span className="font-medium text-gray-100">Fix applied: </span>
                                {pm.fixApplied}
                            </p>
                            <p className="text-xs text-gray-500">
                                Generated by: {pm.generatedBy}
                            </p>
                        </div>
                    ))
                )}
            </div>
        </Layout>
    );
}

export default PostmortemsPage;